before_install:
    - npm i -g npm@latest
    - npm i -g greenkeeper-lockfile@1
before_script:
    - greenkeeper-lockfile-update
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
script:
    - npm run eslint
    - npm run test
after_script:
    - greenkeeper-lockfile-upload
branches:
    only:
        - master
        - /^greenkeeper/.*$/
language: node_js
node_js:
    - 9
    - 10
